version: "3.8"


services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-2022
    environment:
      SA_PASSWORD: "pass@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  

networks:
  app-network:
    driver: bridge